---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - webapp.evolutica.co.za
  resources:
  - envinjects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.evolutica.co.za
  resources:
  - envinjects/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.evolutica.co.za
  resources:
  - envinjects/status
  verbs:
  - get
  - patch
  - update
