apiVersion: webapp.evolutica.co.za/v1
kind: EnvInject
metadata:
  labels:
    app.kubernetes.io/name: envinject
    app.kubernetes.io/instance: envinject-sample
    app.kubernetes.io/part-of: go-custom-k8s-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: go-custom-k8s-operator
  name: envinject-sample
spec:
  # TODO(user): Add fields here
